#!/bin/bash
set -x
set -e
set -o pipefail

BUILDROOT=$HOME
INWORK=false
if [[ -d /work/$USER ]]
then
    echo "Detected /work dir, using that with symlinks to $HOME"
    INWORK=true
    BUILDROOT=/work/$USER
fi

SDIR=$BUILDROOT/$SDIR
BDIR=$BUILDROOT/$BDIR
IDIR=$BUILDROOT/$IDIR

echo "Building: SDIR = $SDIR"
echo "Building: BDIR = $BDIR"
echo "Building: IDIR = $IDIR"
echo "Building: $CMAKE_BUILD_TYPE"


if [[ -d "$SDIR" ]]
then
    echo "Using existing llvm project"
else
    echo "Clone llvm into $SDIR"
    git clone https://github.com/llvm/llvm-project.git $SDIR
fi

cd $SDIR

if [[ -d "ROCT-Thunk-Interface" ]]
then
    echo "Using existing roct"
else
    git clone https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface.git -b roc-4.5.x
fi

if [[ -d "ROCR-Runtime" ]]
then
    echo "Using existing rocr"
else
    git clone https://github.com/RadeonOpenCompute/ROCR-Runtime.git -b rocm-4.5.x
    # This can be disabled by environment variable, but LLVM's testing does not pass that
    # environment variable along. So clobber it in the source directly.
    sed -i 's/os::GetEnvVar("HSA_IGNORE_SRAMECC_MISREPORT")/"1"/' ROCR-Runtime/src/core/util/flag.h

    # patch enum

    cat <<'EOF' | git apply
diff --git a/src/inc/hsa.h b/src/inc/hsa.h
index d8fdd47..def0c39 100644
--- a/src/inc/hsa.h
+++ b/src/inc/hsa.h
@@ -998,7 +998,17 @@ typedef enum {
    * Minor version of the HSA runtime specification supported by the
    * agent. The type of this attribute is uint16_t.
    */
-  HSA_AGENT_INFO_VERSION_MINOR = 22
+  HSA_AGENT_INFO_VERSION_MINOR = 22,
+
+  /**
+   * This enum does not have a fixed underlying type, thus in C++ post D2338:
+   * If the enumeration type does not have a fixed underlying type, the value is
+   * unchanged if the original value is within the range of the enumeration
+   * values (9.7.1 [dcl.enum]), and otherwise, the behavior is
+   * undefined.
+   * Thus increase the range of this enum to encompass vendor extensions.
+   */
+  HSA_AGENT_INFO_UNUSED_WORKAROUND_D2338 = INT32_MAX

 } hsa_agent_info_t;

EOF

fi

if [[ -d "ROCm-Device-Libs" ]]
then
    echo "Using existing device libs"
else
    # fractionally better odds of amd-stg-open building with trunk, but means the sed hacks
    # below will rot faster

    git clone https://github.com/RadeonOpenCompute/ROCm-Device-Libs.git -b amd-stg-open
    #sed -i 's$add_subdirectory(opencl)$# add_subdirectory(opencl)$g' ROCm-Device-Libs/CMakeLists.txt
    #sed -i 's$sys::fs::F_None$sys::fs::OF_None$' ROCm-Device-Libs/utils/prepare-builtins/prepare-builtins.cpp
    #rm -f ROCm-Device-Libs/ockl/src/dots.cl # doesn't build

    #rm -f ROCm-Device-Libs/ockl/src/gaaf.cl # doesn't build

    #rm -rf ROCm-Device-Libs/hc # several files fail with error: Opaque pointers are only supported in -opaque-pointers mode
    

        cat <<'EOF' | git apply
diff --git a/utils/prepare-builtins/CMakeLists.txt b/utils/prepare-builtins/CMakeLists.txt
index 8f1505f..6366196 100644
--- a/utils/prepare-builtins/CMakeLists.txt
+++ b/utils/prepare-builtins/CMakeLists.txt
@@ -22,7 +22,7 @@ endif()
 
 add_executable(prepare-builtins prepare-builtins.cpp)
 set_target_properties(prepare-builtins PROPERTIES
-  CXX_STANDARD 14
+  CXX_STANDARD 17
   CXX_STANDARD_REQUIRED Yes
   CXX_EXTENSIONS No)
 llvm_update_compile_flags(prepare-builtins)
EOF
fi

# amd-stg-open cmake assumes it is called this and up one level
cd ..
ln -s ROCm-llvm-project/ROCm-Device-Libs rocm-device-libs

cd -


if [ "$INWORK" = true ]
then
    echo "Hard reset links in $HOME to $BUILDROOT"
    for DIR in $SDIR $BDIR $IDIR; do
        rm -rf $HOME/$(basename $DIR)
        ln -sf $DIR $HOME/$(basename $DIR)
    done
fi

echo "Clean out build and install directories"
mkdir -p $BDIR
rm -rf $BDIR/*
mkdir -p $IDIR
rm -rf $IDIR/*

# Aomp tests assume a script in ~ this dir which returns a string for the gfx
mkdir -p $IDIR/bin
echo '#!/bin/bash' > $IDIR/bin/mygpu
echo 'echo $('$IDIR'/bin/amdgpu-arch | uniq)' >> $IDIR/bin/mygpu
chmod +x $IDIR/bin/mygpu

# todo: actually compute it, possibly based on available ram

CMAKE_COMMON="-DCMAKE_C_COMPILER=`which gcc` -DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_INSTALL_PREFIX=$IDIR -DOPENMP_ENABLE_LIBOMPTARGET_PROFILING=OFF -DLLVM_ENABLE_ASSERTIONS=On -DLLVM_PARALLEL_LINK_JOBS=$(( ($(nproc) + 7)/8 )) "

cd $BDIR
rm -rf roct && mkdir roct && cd roct
cmake $SDIR/ROCT-Thunk-Interface/ $CMAKE_COMMON $CMAKE_BUILD_TYPE -DBUILD_SHARED_LIBS=OFF
make -j `nproc` && make -j `nproc` install

# cmake doesn't build both static and shared but could do so separately
# there's some commented out logic below for putting a link to the .so where
# tests can find it which we don't want to do with a static build
cd $BDIR
rm -rf rocr && mkdir rocr && cd rocr
cmake $SDIR/ROCR-Runtime/src/ -DIMAGE_SUPPORT=OFF $CMAKE_COMMON $CMAKE_BUILD_TYPE -DBUILD_SHARED_LIBS=ON
make -j `nproc` && make -j `nproc` install


cd $BDIR 
rm -rf llvm && mkdir llvm
cd llvm
# -DLIBOMPTARGET_BUILD_NVPTX_BCLIB=TRUE # useful on wx, breaks build on r7

if [[ -d "/usr/local/cuda-11" ]]
then
    echo "Got a cuda-11 install on disk, using it"
    # Doesn't suffice to hit LIBOMPTARGET_DEP_CUDA_FOUND, a curse on cmake
    CUDA="-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11"
else
    CUDA=""
fi

# force dlopen hsa because it's more likely to break
# force dlopen cuda because cuda autodetection is broken and because
# forcing it on is part of the dance to enable tests
# dlopen subset of hsa fails to build printf (which uses hsa.hpp)
#       -DLIBOMPTARGET_ENABLE_DEBUG=ON \
# enable debug may be making all the filecheck tests fail, annoyingly
#      -DLIBOMPTARGET_FORCE_DLOPEN_LIBCUDA=TRUE \
#      -DDEVICELIBS_ROOT=$SDIR/ROCm-Device-Libs probably don't need this

cmake $SDIR/llvm $CMAKE_COMMON $CMAKE_BUILD_TYPE \
      -DLLVM_ENABLE_PROJECTS="clang;lld" \
      -DOPENMP_ENABLE_LIBOMPTARGET_HSA=TRUE \
      -DENABLE_AMDGPU_ARCH_TOOL=TRUE \
      $CUDA \
      -DLIBOMPTARGET_FORCE_DLOPEN_LIBCUDA=FALSE \
      -DLIBOMPTARGET_FORCE_DLOPEN_LIBHSA=TRUE \
      -DLIBOMPTARGET_BUILD_NVPTX_BCLIB=TRUE \
      -DLIBOMPTARGET_BUILD_AMDGPU_BCLIB=TRUE \
      -DLIBOMPTARGET_BUILD_CUDA_PLUGIN=TRUE \
      -DLIBOMPTARGET_BUILD_AMDGPU_PLUGIN=TRUE \
      -DLLVM_TARGETS_TO_BUILD="X86;AMDGPU" \
      -DLLVM_ENABLE_RUNTIMES="openmp" \
      -GNinja

BUILDTOOL="make -j`nproc`"
BUILDTOOL="ninja"

$BUILDTOOL

# libomptarget tests no longer use LD_LIBRARY_PATH, put a link to libhsa next to the plugin

FROM=$(find $BDIR -iname libhsa-runtime64.so)
LIBOMP=$(find $BDIR -iname libomptarget.rtl.amdgpu.so)
if [[ -e $LIBOMP ]]
then
echo "Link hsa $FROM to dirname $LIBOMP"
TO=$(dirname $LIBOMP)
ln -sf $FROM $TO
else
echo "Can't find libomptarget.rtl.amdgpu.so, don't try to ln hsa"
fi
set +e
$BUILDTOOL check-all 
set -e
$BUILDTOOL install # often want install to succeed even if tests dont

# device libs needs a recent llvm and doesn't honour cmake configuration
# it will use whatever clang find_package returns, and one place that looks is the path
cd $BDIR
rm -rf devlibs && mkdir devlibs && cd devlibs
export PATH=$IDIR/bin:$PATH
cmake $SDIR/ROCm-Device-Libs $CMAKE_COMMON $CMAKE_BUILD_TYPE -GNinja
$BUILDTOOL && $BUILDTOOL install
# clang doesn't handle ABI breaks in device libs well and rocm doesn't bother with
# backwards compatibility, may need stuff like:
# touch /opt/rocm/lib/opencl.bc
